# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-02 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180301_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Land', 'Land')], max_length=200, null=True),
        ),
    ]
