# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-19 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_property_lot_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='parking_space',
            field=models.IntegerField(default=0),
        ),
    ]
