# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-11 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_property_parking_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(default='Sold', max_length=200),
        ),
    ]
