# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-16 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_property_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
                ('picture_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Property')),
            ],
        ),
    ]
