# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180417_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='favorites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='tours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
