# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180417_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='avetiz_agent',
            field=models.CharField(default='Faith', max_length=200),
        ),
    ]
