# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_property_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.CharField(default='2017', max_length=30, null=True),
        ),
    ]
