# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180420_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(default='2017', null=True),
        ),
    ]
