# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180420_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
