# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180430_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='developer',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
