# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180430_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mortage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=200)),
                ('website', models.URLField()),
            ],
        ),
    ]
