# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_mortage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortage',
            name='logo',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
