# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-15 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_mortage_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='eat_in_kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='no_of_fireplace',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='no_of_kitchen',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='no_of_stove',
            field=models.IntegerField(default=1),
        ),
    ]
